name: rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  helpers:
    name: Helpers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=./helpers/Cargo.toml

      - name: Check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=./helpers/Cargo.toml -- --check

  days:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        day: [ 1, 2, 3, 4, 5, 6, 7, 8, 9 ]

    name: Day ${{ matrix.day }}
    steps:
      - uses: actions/checkout@v2

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=./day${{ matrix.day }}/Cargo.toml

      - name: Check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=./day${{ matrix.day }}/Cargo.toml -- --check

      - name: Run
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path=./day${{ matrix.day }}/Cargo.toml --release
